proxy:
  secretToken: "fff9010b1ff9d7ab35e67556517df9599af4773734e5de0caa251093b881a7eb"
singleuser:
  image:
    name: djgagne/ams-ml-python-course
    tag: gpu
  defaultUrl: "/lab"
  cpu:
    limit: 1
    guarantee: 1
  memory:
    limit: 10G
    guarantee: 9G
  storage:
    type: none
  resources:
    limits:
      nvidia.com/gpu: 1
auth:
  admin:
    users:
      - djgagne@ou.edu
      - ryan.lagerquist@ou.edu
      - mickelso@ucar.edu
      - gherman@rams.colostate.edu
  whitelist:
    users:
      - lak@google.com
      - djgagne@ou.edu
      - ryan.lagerquist@ou.edu
      - mickelso@ucar.edu
      - gherman@rams.colostate.edu
      - caecar1986@qq.com
      - brainard92@yahoo.com
      - sue.chen@nrlmry.navy.mil
      - adityachoukulkar@gmail.com
      - jlc248@gmail.com
      - judah.l.cleveland.ctr@mail.mil
      - austin.coleman@ttu.edu
      - saicumbulam@earthnetworks.com
      - dionne.pierre.3@hydro.qc.ca
      - b.fjukstad@met.no
      - eric@intellovations.com
      - feng.gao.met@gmail.com
      - lgloeckler@albany.edu
      - windrunnerxc@gmail.com
      - sarah.griffin@ssec.wisc.edu
      - dhall@nvidia.com
      - meh9phx@gmail.com
      - thomas.huang@jpl.nasa.gov
      - paul.iniguez@noaa.gov
      - Jdjacob@okstate.edu
      - allan.just@mssm.edu
      - jenny.kafka@rutgers.edu
      - hkamangir@islander.tamucc.edu
      - alexander.ken@noaa.gov
      - mu-chieh.ko@noaa.gov
      - hugo.landry@canada.ca
      - alang@albany.edu
      - jefflapierre6@gmail.com
      - ryan.leach@noaa.gov
      - russell.p.manser@ttu.edu
      - tsm1004@wildcats.unh.edu
      - redsoxfan824@gmail.com
      - amanda.mitchell@noaa.gov
      - kate.d.musgrave@gmail.com
      - cnguyen13@islander.tamucc.edu
      - mpashaei@islander.tamucc.edu
      - rahmes@yahoo.com
      - tregan@mountwashington.org
      - timothy.sliwinski@ttu.edu
      - tallguy257@gmail.com
      - gstoss@ucar.edu
      - jim.z.tang@gmail.com
      - mtewari@us.ibm.com
      - lidia.trailovic@noaa.gov
      - ktyle@atmos.albany.edu
      - jvankerk@uwo.ca
      - erikw789@gmail.com
      - wimmers@ssec.wisc.edu
      - tjwixtrom@gmail.com
      - alexa.zabaske@tamu.edu
cull:
    enabled: False
hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']
    c.KubeSpawner.extra_resource_limits = {"nvidia.com/gpu": "1"}
