proxy:
  secretToken: "fff9010b1ff9d7ab35e67556517df9599af4773734e5de0caa251093b881a7eb"
singleuser:
  image:
    name: djgagne/ams-ml-python-course
    tag: latest
  defaultUrl: "/tree"
  cpu:
    limit: 1
    guarantee: 1
  memory:
    limit: 10G
    guarantee: 9G
  storage:
    type: none
  resources:
    limits:
      nvidia.com/gpu: 1
auth:
  admin:
    users:
      - djgagne@ou.edu
      - ryan.lagerquist@ou.edu
      - mickelso@ucar.edu
      - gherman@rams.colostate.edu
  whitelist:
    users:
      - user01
      - user02
      - user03
      - user04
      - user05
      - user06
      - user07
      - user08
      - user09
      - user10
      - user11
      - user12
      - user13
      - user14
      - user15
      - user16
      - user17
      - user18
      - user19
      - user20
      - user21
      - user22
      - user23
      - user24
      - user25
cull:
    enabled: False
hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']
    c.KubeSpawner.extra_resource_limits = {"nvidia.com/gpu": "1"}
